importing  numpy,numarry creation

In [ ]:
import numpy as np #import numpy
print("Numpy Version ", np. _version_)
arr = np.array ([8, 4, 6, 0, 2]) #numpy array creation
print(arr) #printing numpy array

Task
1. Create a 3x3 matrix with values ranging from 2 to 10, convert array to a float type. Write a Python program to find the maximum and minimum value of flattened array.


In [4]:
import numpy as np

arr = np.arange(2, 11).reshape(3, 3)

arr = arr.astype(float)

flat_arr = arr.reshape(-1)

maximum_value = np.max(flat_arr)
minimum_value = np.min(flat_arr)

print("Matrix:\n", arr)
print("Flattened Array:", flat_arr)
print("Maximum Value:", maximum_value)
print("Minimum Value:", minimum_value)


Matrix:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
Flattened Array: [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Maximum Value: 10.0
Minimum Value: 2.0
